- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - xorg
    - kitty
    - vlc
    - gimp
    - git
    - thefuck
    - tmux
    - lsd
    - vim
    - source-highlight
    - tree
   state: present

- name: Install ImageMagick (optional dependency for image rendering)
  pacman:
    name: imagemagick
    state: present